### ISSUE TITLE
Not understand with purchase

### ISSUE THREAD

**Issue by vqoley** [oneconnectapi/OneConnectSdk-demo-android#11]
i not understand with purchase. i try purchase Ultimate Plus Plan its said "Recurring No" but its said "Membership Period 3 Months". what is meaning? is that after months, i cannot use it anymore?

**Comment by oneconnectapi** [comment]
Hello, "Recurring No" mean you will not charged automatically for renew. You will need to renew manually after expire the plan, All Plan validity is 3 Months. Thanks...
