### ISSUE TITLE
VPN Servers not working

### ISSUE THREAD

**Issue by solver44** [oneconnectapi/OneConnectSdk-demo-android#17]
Hello, I downloaded the (OneConnectSdk-demo-android) repository to my computer and launched it by changing the oneconnect api and the servers were displayed in the application, but it doesn’t connect to any servers, the application got stuck in the process of authenticating

tell me what could be the reason

![Screenshot_2](https://user-images.githubusercontent.com/74422066/236663093-3b42487d-a08d-402a-8a65-d0c7c3d1a14a.png)

**Comment by oneconnectapi** [comment]
Go to your pc c/users/**pc_name**/.gradle
And **delete** this .gradle folder
And after that set **version 1.0.9**
And test server in demo project
