### ISSUE TITLE
Server connect but return empty array

### ISSUE THREAD

**Issue by waseem-terafort** [oneconnectapi/OneConnectSdk-demo-android#21]
i have purchased the premium servers as well but when code runs in splash its return empty both free and premium server 

 runBlocking {
            launch(Dispatchers.IO) {
                try {
                    Log.d("MyApp", "Coroutine started") // Log that the coroutine has started
                    val oneConnect = OneConnect()
                    oneConnect.initialize(this@SplashActivity, "2w0QvmDcWoNfZWTmEukdhdjskskljkskfXSsF8JAu4zbvgLka2Br7u1ioLpiIvr9UE8Y6lw")
                    val response = oneConnect.fetch(true)
                    Log.d("MyApp", "API Response: $response")
                    try {
                        Constants.FREE_SERVERS = oneConnect.fetch(true) ////  this part return emptylist
                        Constants.PREMIUM_SERVERS = oneConnect.fetch(true)//// this part return empty list
                        Log.d("MyApp", "Data fetched successfully") // Log that data was fetched successfully
                    } catch (e: IOException) {
                        e.printStackTrace()
                        Log.e("MyApp", "IOException: " + e.message) // Log any IOException
                    }
                } catch (e: Exception) {
                    e.printStackTrace()
                    Log.e("MyApp", "Exception: " + e.message) // Log any other exceptions
                }
            }
        }

comment mention where list is empty in code this code is running in splash on create

**Comment by MirzaQais** [comment]
How did you find the solution in demo project 
i am getting the null array also.

**Comment by waseem-GitHub-Live** [comment]
@MirzaQais  Check server it must be closed from admin side , login in your account oneconnect and on the servers or change the key , key will genrate when u give your app package name

**Comment by MirzaQais** [comment]
But on demo app it should work ?

**Comment by waseem-GitHub-Live** [comment]
@MirzaQais Yes

**Comment by MirzaQais** [comment]
It is not working on demo, how to test it then?
