### ISSUE TITLE
server not connected

### ISSUE THREAD

**Issue by akashsingh7895** [oneconnectapi/OneConnectSdk-demo-android#24]
i am creating a vpn app using oneConneting sdk , in my case server is fetch (Uk Manchester) but vpn is not connecting 
![WhatsApp Image 2023-11-24 at 21 57 42_52e17842](https://github.com/oneconnectapi/OneConnectSdk-demo-android/assets/90977694/7568eb59-8109-4f04-a132-a0e9509a1d57)
![WhatsApp Image 2023-11-25 at 10 35 30_899f3522](https://github.com/oneconnectapi/OneConnectSdk-demo-android/assets/90977694/afda86e8-e34a-4105-89b1-907ddfc2ddcc)

**Comment by oneconnectapi** [comment]
Use demo project or follow doc https://oneconnect-1.gitbook.io/oneconnect-sdk-for-android-doc/
