### ISSUE TITLE
Issue with VPN Connection on Android 8 Devices with arm-v8a Architecture

### ISSUE THREAD

**Issue by Bitechpvt** [oneconnectapi/OneConnectSdk-demo-android#27]
I have encountered the issue with the OneConnect VPN service on devices running Android 8 and equipped with the arm64-v8a architecture. The VPN connection is not functioning as expected on these devices.

Devices: Samsung S6, S7

4 cores processor

**Comment by oneconnectapi** [comment]
**Email from oneconnect contact us**
